package com.capstone.mcp;

/**
 * MCPSeleniumIntegration — Model Context Protocol (MCP) demonstration layer.
 *
 * ============================================================
 * WHAT IS MCP (Model Context Protocol)?
 * ============================================================
 * MCP is an open protocol developed by Anthropic that allows AI models
 * (like Claude) to interact with external tools and systems in a
 * standardized, structured way.
 *
 * In the context of test automation, MCP enables:
 * 1. SCRIPT GENERATION: AI generates Selenium test code by understanding
 *    the DOM structure of a web page
 * 2. INTELLIGENT LOCATORS: AI suggests the most stable locator strategy
 *    for a given element based on DOM analysis
 * 3. SELF-HEALING: When a locator fails, AI analyzes the current DOM
 *    and suggests an updated locator
 * 4. TEST MAINTENANCE: AI can update outdated test scripts when the
 *    application UI changes
 *
 * ============================================================
 * HOW MCP WORKS IN SELENIUM AUTOMATION:
 * ============================================================
 * Traditional flow:   Developer → writes locators manually → tests break on UI changes
 * MCP-assisted flow:  AI analyzes DOM → generates locators → self-heals on changes
 *
 * The MCP Selenium server (github.com/angiejones/mcp-selenium) exposes
 * browser interaction capabilities as MCP tools that AI can call.
 *
 * ============================================================
 * SETUP INSTRUCTIONS FOR MCP-SELENIUM:
 * ============================================================
 * 1. Install Node.js (v18+)
 * 2. npm install -g @angiejones/mcp-selenium
 * 3. Configure Claude Desktop or Claude API to use the MCP server
 * 4. The AI can then:
 *    - navigate_to(url)
 *    - find_element(strategy, value)
 *    - take_screenshot()
 *    - generate_test_script(page_url, test_objective)
 *
 * ============================================================
 * DEMO: What MCP-generated code looks like
 * ============================================================
 * When you tell Claude (via MCP): "Generate a Selenium test for logging
 * into https://practice.expandtesting.com/notes/app"
 *
 * MCP flow:
 * 1. Claude calls navigate_to("https://practice.expandtesting.com/notes/app")
 * 2. Claude calls take_screenshot() → analyzes the DOM
 * 3. Claude identifies: email input (#email), password input (#password), submit button
 * 4. Claude generates the code below based on actual DOM inspection
 *
 * This is fundamentally different from Claude writing code from memory —
 * it SEES the actual page and generates locators from the real DOM.
 */

import com.capstone.config.ConfigManager;
import com.capstone.drivers.DriverManager;
import com.capstone.utils.WaitUtil;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.Map;

/**
 * MCPSeleniumIntegration demonstrates how MCP-generated locators and
 * AI-assisted scripts integrate into the existing framework.
 *
 * This class simulates what an MCP server would return when asked to
 * analyze the Notes App and generate interaction scripts.
 */
public class MCPSeleniumIntegration {

    private static final Logger log = LoggerFactory.getLogger(MCPSeleniumIntegration.class);

    // ============================================================
    // MCP-GENERATED LOCATOR MAP
    // (In real MCP, these are returned by the AI after DOM analysis)
    // ============================================================
    // The AI inspected the actual Notes App DOM and returned these locators.
    // Crucially, the AI ranked them: ID > data-testid > aria-label > CSS > XPath
    // This ranking ensures maximum locator stability.

    private static final Map<String, By[]> MCP_GENERATED_LOCATORS = new HashMap<>();

    static {
        // Login page locators — generated by MCP DOM analysis
        MCP_GENERATED_LOCATORS.put("login.email", new By[]{
            By.id("email"),                                    // Primary (most stable)
            By.name("email"),                                  // Fallback 1
            By.cssSelector("input[type='email']"),             // Fallback 2
            By.xpath("//input[@placeholder='Enter your email']") // Last resort
        });

        MCP_GENERATED_LOCATORS.put("login.password", new By[]{
            By.id("password"),
            By.name("password"),
            By.cssSelector("input[type='password']"),
            By.xpath("//input[@placeholder='Enter your password']")
        });

        MCP_GENERATED_LOCATORS.put("login.submit", new By[]{
            By.id("login"),
            By.cssSelector("button[type='submit']"),
            By.xpath("//button[contains(text(),'Login')]")
        });

        // Notes page locators
        MCP_GENERATED_LOCATORS.put("notes.add_button", new By[]{
            By.id("add-note"),
            By.cssSelector("a[href*='notes/new'], button[data-target='#add-note-modal']"),
            By.xpath("//a[contains(@class,'btn') and contains(.,'Add Note')]")
        });

        MCP_GENERATED_LOCATORS.put("notes.title_input", new By[]{
            By.id("title"),
            By.name("title"),
            By.cssSelector("input#title, input[placeholder*='Title']")
        });

        MCP_GENERATED_LOCATORS.put("notes.description_input", new By[]{
            By.id("description"),
            By.name("description"),
            By.cssSelector("textarea#description")
        });

        MCP_GENERATED_LOCATORS.put("notes.category_select", new By[]{
            By.id("category"),
            By.name("category"),
            By.cssSelector("select#category")
        });

        MCP_GENERATED_LOCATORS.put("notes.save_button", new By[]{
            By.id("note-submit"),
            By.cssSelector("button[type='submit']"),
            By.xpath("//button[text()='Create Note' or text()='Save Note']")
        });
    }

    // ============================================================
    // MCP SELF-HEALING FIND ELEMENT
    // ============================================================

    /**
     * Finds an element using MCP-generated locator hierarchy.
     * If the primary locator fails, automatically tries fallbacks.
     * This is the "self-healing" behavior described in the capstone requirements.
     *
     * @param driver       The WebDriver instance
     * @param locatorKey   Key from MCP_GENERATED_LOCATORS map
     * @return             Found WebElement
     * @throws RuntimeException if all locator strategies fail
     */
    public static WebElement findWithMCPLocators(WebDriver driver, String locatorKey) {
        By[] locatorStrategies = MCP_GENERATED_LOCATORS.get(locatorKey);

        if (locatorStrategies == null) {
            throw new IllegalArgumentException(
                "No MCP-generated locators found for key: '" + locatorKey + "'");
        }

        for (int i = 0; i < locatorStrategies.length; i++) {
            By locator = locatorStrategies[i];
            try {
                WebElement element = WaitUtil.waitForVisible(driver, locator, 5);
                if (i > 0) {
                    // Primary locator failed — log that healing occurred
                    log.warn("MCP SELF-HEALING: Primary locator failed for '{}'. " +
                             "Used fallback #{}: {}", locatorKey, i, locator);
                    // In a real MCP implementation, this would trigger:
                    // 1. A notification to the team about the broken primary locator
                    // 2. AI analysis of why it changed (DOM diff)
                    // 3. Suggestion to update the primary locator
                }
                log.debug("MCP locator resolved for '{}' using strategy #{}: {}",
                         locatorKey, i, locator);
                return element;
            } catch (Exception e) {
                log.debug("MCP locator attempt #{} failed for '{}': {} → {}",
                         i, locatorKey, locator, e.getClass().getSimpleName());
            }
        }

        // All strategies failed — capture diagnostic info
        String pageSource = driver.getPageSource().substring(0, Math.min(500, driver.getPageSource().length()));
        throw new RuntimeException(
            "MCP SELF-HEALING EXHAUSTED: All " + locatorStrategies.length +
            " locator strategies failed for key: '" + locatorKey + "'\n" +
            "Current URL: " + driver.getCurrentUrl() + "\n" +
            "Page source excerpt: " + pageSource);
    }

    // ============================================================
    // MCP SCRIPT: AI-GENERATED COMPLETE LOGIN FLOW
    // ============================================================

    /**
     * Demonstrates an MCP-generated complete login script.
     * The AI analyzed the login page and generated this sequence.
     *
     * In a real MCP workflow, you'd prompt Claude:
     * "Using MCP Selenium, generate a login script for the Notes app at [URL]"
     * Claude would navigate, inspect, and return this code.
     */
    public static void mcpGeneratedLogin(WebDriver driver, String email, String password) {
        log.info("MCP-generated login script executing...");

        // Step 1: Ensure we're on the login page
        String currentUrl = driver.getCurrentUrl();
        if (!currentUrl.contains("login")) {
            driver.get(ConfigManager.getInstance().getBaseUrl() + "/login");
        }

        // Step 2: Use MCP locators (self-healing)
        WebElement emailField = findWithMCPLocators(driver, "login.email");
        emailField.clear();
        emailField.sendKeys(email);

        WebElement passwordField = findWithMCPLocators(driver, "login.password");
        passwordField.clear();
        passwordField.sendKeys(password);

        // Step 3: Capture UI performance metric (MCP performance check)
        long beforeClick = System.currentTimeMillis();
        findWithMCPLocators(driver, "login.submit").click();

        // Step 4: Wait for navigation and measure DOM ready time
        WaitUtil.waitForPageLoad(driver);
        long afterLoad = System.currentTimeMillis();

        long navigationTime = afterLoad - beforeClick;
        log.info("MCP UI TIMING: Login navigation completed in {}ms (threshold: {}ms)",
                navigationTime,
                ConfigManager.getInstance().getInt("ui.page.load.time.ms"));

        if (navigationTime > ConfigManager.getInstance().getInt("ui.page.load.time.ms")) {
            log.warn("UI PERFORMANCE DEGRADATION: Login took {}ms (exceeds {}ms threshold)",
                    navigationTime,
                    ConfigManager.getInstance().getInt("ui.page.load.time.ms"));
        }

        log.info("MCP login script completed. Current URL: {}", driver.getCurrentUrl());
    }

    // ============================================================
    // MCP PERFORMANCE MEASUREMENT
    // ============================================================

    /**
     * Captures browser Navigation Timing API metrics.
     * WHY: These are real browser-measured timings, not just Selenium timestamps.
     * The Navigation Timing API (window.performance.timing) records:
     * - DNS lookup time
     * - TCP connection time
     * - Time to First Byte (TTFB)
     * - DOM Interactive (JS execution started)
     * - DOM Content Loaded (HTML parsed)
     * - Load Complete (all resources loaded)
     */
    public static Map<String, Long> captureNavigationTimings(WebDriver driver) {
        JavascriptExecutor js = (JavascriptExecutor) driver;

        // Execute JS to extract Navigation Timing API values
        Map<String, Object> rawTimings = (Map<String, Object>) js.executeScript(
            "var t = window.performance.timing;" +
            "return {" +
            "  'dnsLookup':        t.domainLookupEnd - t.domainLookupStart," +
            "  'tcpConnect':       t.connectEnd - t.connectStart," +
            "  'serverResponse':   t.responseStart - t.requestStart," +
            "  'domInteractive':   t.domInteractive - t.navigationStart," +
            "  'domContentLoaded': t.domContentLoadedEventEnd - t.navigationStart," +
            "  'pageLoad':         t.loadEventEnd - t.navigationStart" +
            "};"
        );

        Map<String, Long> timings = new HashMap<>();
        rawTimings.forEach((k, v) -> timings.put(k, ((Number) v).longValue()));

        // Log summary
        log.info("===== MCP UI PERFORMANCE TIMINGS =====");
        log.info("  DNS Lookup:          {}ms", timings.get("dnsLookup"));
        log.info("  TCP Connect:         {}ms", timings.get("tcpConnect"));
        log.info("  Server Response:     {}ms", timings.get("serverResponse"));
        log.info("  DOM Interactive:     {}ms", timings.get("domInteractive"));
        log.info("  DOM Content Loaded:  {}ms", timings.get("domContentLoaded"));
        log.info("  Full Page Load:      {}ms", timings.get("pageLoad"));
        log.info("=======================================");

        return timings;
    }
}
